### ISSUE TITLE
[CharView] Equip Component

### ISSUE THREAD

**Issue by Gianluks90** [Gianluks90/adventurer-studio#146]
Implementazione di un nuovo componente per gestire l'equipaggiamento di un PG. Nello status (colonna di sinistra) sotto ai parametri vitali dove ci sono CA, Velocità, ecc... occorre implementare un nuovo piccolo componente che eredita in aspetto dall'inventario ma in formato più piccolo. Il componente mostra gli oggetti "Equipaggiati" (prop. `weared`) e calcola CA e Danni a seconda di ciò.  Infine un elenco espandibile o nascosto di tutti i tratti, tratti degli artefatti, effetti di maledizioni e altro che si portano dietro le armi, viene mostrato appena sotto;

**TODO**
- [x] Nuovo componente in `utilities` chiamato `EquipmentComponent`;
- [x] Il componente prende in Input `character` per poter accedere alle info del PG e all'inventario;
- [x] Un button dedicato apre una dialog all'interno del Componente che permette la scelta dell'equipaggiamento;
- [x] Un altro button permette di cambiare set di armi (sono previsti vari set) ciclicamente;

**Dialog - Gestione**
- [x] Creare un formGroup ad hoc per questa funzione con: `armor: Item`, `others: Item[]`, `sets: FormArray`;
- [x] Al FormControlName `armor` è da collegare una select semplice con tutti gli oggetti che hanno `CA > 0`e non sono `shield`;
- [x] Al FormControlName `others` si collega una select `multiple` con tutti gli oggetti che possono essere equipaggiati (forse è necessario un nuovo flag 'wearable' per distinguerli?);
- [x] Al FormControlName `sets` bisogna collegare una funzioni che crei dei FormGroup con ControlName: `leftHand` (obbligatorio) e `rightHand` e un `name` (obbligatorio);

**Cambio Set**
- [x] Il button "Cambio set" con icona "restart_alt" (credo) è disabilitato se sets.length <= 1;
- [x] Se attivo, alla pressione, mostrare nell'elenco gli oggetti corrispondenti e ricalcolare i Danni; 

**Modifiche da fare all'InventoryComponent**
- [x] Rimuovere il tasto "Equipaggia" dal bottom-sheet e dalla dialog di inserimento/modifica;
